### ISSUE TITLE
Start up crash with version 5.2.1

### ISSUE THREAD

**Issue by DWX12** [cybercat5555/BetterAnimals#13]
New version seems to be having compatibility issues with some mods. Two at the moment, but I'm sure there's probably more to be seen:

Dye it Yourself:
https://paste.dimdev.org/kakewirugi.mccrash

Wolf Armor:
https://paste.dimdev.org/ufalabavev.mccrash

Both are the latest versions of those mods.

If I find more issues with additional mods, I'll be sure to post them.

**Comment by JoelZBub** [comment]
I should stay out of this, but....
This is clearly displayed on the download page:
![Armor](https://user-images.githubusercontent.com/12024500/58062754-8a9ec200-7b49-11e9-8ce6-f13b2bec287e.png)

**Comment by itsmeow** [comment]
Unfortunately we cannot offer compatibility for either of these mods, it would have to be on their end.

**Comment by DWX12** [comment]
Well that was an oversight on my part, I apologize for that. Seems weird that they were working with the previous versions. Not sure what the issue could be with Dye it Yourself though.

Thank you for replying to me atleast.
