### ISSUE TITLE
Better Animal Models  1.14.4-5.2.1

### ISSUE THREAD

**Issue by Diogenes-Inajar** [cybercat5555/BetterAnimals#18]
Noob here

whenever I load BA for mc 1.14.4 with forge (I have tried 28.0.44, 28.0.45, 28.0.46, 28.1.0), I get the same message that the mod requires an earlier version of forge, which seems weird to me.
This is the version of the mod I used: https://www.curseforge.com/minecraft/mc-mods/better-animal-models/files/2758442

where do I go wrong?

**Comment by itsmeow** [comment]
not home rn try 28.0.93 or 91

**Comment by Diogenes-Inajar** [comment]
using 28.0.93 did the job. thank you!
