### ISSUE TITLE
Wolf Armor & Wolf Armor Sophisticated Wolves Compat

### ISSUE THREAD

**Issue by IdrisQe** [cybercat5555/BetterAnimals#19]
https://www.curseforge.com/minecraft/mc-mods/wolf-armor-and-storage
This mod allows you to equip tamed wolves with armor and chests. It has support for Sophisticated Wolves (or maybe Sophisticated Wolves has support for it?)

Better Animal Models currently supports Sophisticated Wolves, but doesn't support Wolf Armor to my knowledge, which is unfortunate as the two go great together, and all three together would be amazing.

**Comment by itsmeow** [comment]
In order to this on our side it would require significant reproduction of code from Wolf Armor and a lot of work. Unfortunately this is not something I am wishing or able to do.
