### ISSUE TITLE
Chickens, Cows, and Pigs missing their model

### ISSUE THREAD

**Issue by Rileybutt** [cybercat5555/BetterAnimals#21]
I don't know really know what might be causing this but I did see a issue thread from the past mentioning the chickens and spiders missing their model but that also seems like a different problem.

So I installed the 1.14.4 version of this mod and all was well, I never saw this mod before and honestly I like the models a lot. But then after a while, I'm not sure if it happened after a restart of the game or just at random, my animals reset their models back to the vanilla ones. Just the chickens, cows and pigs though. All other mobs are fine and even the sheep still have their new models from this mod.

At first I thought it might of been Quark as I know it randomizes the textures for those three mobs but after disabling them nothing changed. It was only then I went back to the mod page and saw that shouldn't be an issue at all as this mod says it supports Quark's random animals.

So I'm just kind of at a loss and was wondering if this issue has come up in the past and if there was a way to fix it? I don't know if its something I did wrong with a mod incompatibility or just a bug with this version.

**Comment by itsmeow** [comment]
It is Quark! We haven't added support for Quark 1.14 yet. It's being worked on but we are waiting for Quark to resolve https://github.com/Vazkii/Quark/issues/1790

**Comment by Rileybutt** [comment]
Oh shoot, okay. The problem still persists even after disabling Quark's feature? That's fine then, I can wait. I just wanted to make sure it wasn't an issue with my mod list. Thanks for the reply.
