### ISSUE TITLE
Enchanted Wolves and Wolf Armor compatibility for 1.12.2

### ISSUE THREAD

**Issue by Mizhok** [cybercat5555/BetterAnimals#25]
Currently Minecraft crashes when either or both of the mods together and wolf models are enabled.

**Comment by Mizhok** [comment]
Honestly, it doesn't even need to be visually implemented. I would much prefer having the functionality of these mods even if it means sacrificing their visuals, and there's a very little in Enchanted Wolves.

**Comment by itsmeow** [comment]
It is impossible for us to have compat with these mods, ever likely.
