### ISSUE TITLE
Probably client crush bug

### ISSUE THREAD

**Issue by Krutoy242** [cybercat5555/BetterAnimals#26]
https://github.com/itsmeow/BetterAnimals/blob/master/src/main/java/com/ocelot/betteranimals/client/ReplacementHandler.java#L309

Not sure if `Log` intended instead of `LOG`, but this line was in [crush traceback](https://gist.github.com/Krutoy242/5b5f3ca8108b3dc8fb037e84dbeccbbb)

**Comment by itsmeow** [comment]
Oh wow, oops haha, will fix when I get around to updating.
