### ISSUE TITLE
Most models Defaulting (1.12.2)

### ISSUE THREAD

**Issue by SF362** [cybercat5555/BetterAnimals#27]
So regarding the latest 1.12.2 file, most creatures are still using their default models, exceptions being the Wolf, Ocelot, Mooshroom, and Spider, everything else so far seems to be vanilla.

**Comment by itsmeow** [comment]
HOW

**Comment by SF362** [comment]
If I knew i'd give you the answer and save you time. I've tried it with a load of other mods, and I've tried it as the only mod, results are the same.
Perhaps the other models were over written when you made it (not sure on your process) though I find it odd no one else has brought this up since its been out for half a year
