### ISSUE TITLE
Crash on loadup with Quark 2.4 r280

### ISSUE THREAD

**Issue by SephirothWS** [cybercat5555/BetterAnimals#29]
https://gist.github.com/SephirothWS/2667117677831b1496da2c446b419c09

**Comment by Wilevar** [comment]
Can second this. Same issue with the new Quark update.

**Comment by BedrockLegends** [comment]
![2020-12-17_11 54 35](https://user-images.githubusercontent.com/48525410/102524622-e18ab700-405e-11eb-892e-e44b851a7cc4.png)

**Comment by itsmeow** [comment]
Just use an older version for now, Quark decided to move things around for no reason
