### ISSUE TITLE
Wolf Textures Missing

### ISSUE THREAD

**Issue by AdmAerrol** [cybercat5555/BetterAnimals#30]
Reposting this from curse, as I noticed you asked people to post their issues here.

Sorry if I missed an obvious solution, but I am getting a weird issue with the dogs/wolves: half of their textures don't appear. 
Screenshots: 
![2020-12-29_23 54 05](https://user-images.githubusercontent.com/76768598/103336358-289c8300-4a35-11eb-8e7c-a82c6f29740d.png)

![2020-12-29_23 53 55](https://user-images.githubusercontent.com/76768598/103336365-2cc8a080-4a35-11eb-9e8a-3bace5d89506.png)

Any ideas? I tried disabling my resource pack, so maybe it's a mod incompatibility, but I'm not sure what would be causing it... Maybe Biomes o Plenty?

I guess any known incompatibilities would be helpful, or tips on how to fix the textures being over-written by another mod, haha. 

Great mod otherwise. Thanks!

**Comment by itsmeow** [comment]
This is some mod, I forgot what mod but it tries to replace the wolf texture, but obviously the model has changed from the vanilla one so it ends up looking like that.

**Comment by itsmeow** [comment]
Charm adds wolf variants, I know that is one of them. Any other ideas?

**Comment by AdmAerrol** [comment]
Thanks for the super quick reply! I have the following mods currently installed (sorry for the long list, haha):

1. Biomes O' Plenty
2. Just Enough Items
3. Macaw's Bridges
4. Traveler's Backpack
5. Dungeons Plus
6. Fast Leaf Decay
7. Hwyla (What are you looking at)
8. Inventory Tweaks Renewed
9. Pam's Harvestcraft 2 - Food Extended
10. Pam's Harvestcraft 2 - Food Core
11. Pam's Harvestcraft 2 - Crops
12. Pam's Harvestcraft 2 - Trees
13. Towers of the WIld
14. Iron Chests
15. GraveStone Mod
16. Decorative Blocks
17. Storage Drawers
18. Xaeros's World Map
19. Xaeros's Minimap
20. Ice and Fire: Dragons
21. Citadel
22. Better Animal Models
23. Better Animals Plus

Looking at that list, if it's not Biomes' o Plenty, maybe Ice and Fire: Dragons? But as far as I can tell, it only adds NEW creatures rather than modifying old ones... Is it something in Citadel perhaps? I don't really understand what Citadel does other than being a requirement for Ice and Fire. 

Thanks very much for helping!

**Comment by itsmeow** [comment]
Oh! Is it your texture pack?

**Comment by AdmAerrol** [comment]
.....................I'm an idiot, lol. Sorry! I had previously thought I disabled my texturepack (Dokucraft High: https://dokucraft.co.uk/resource-packs/high/ ) but I actually just moved it down the load-order. Actually disabling it fixed the problem.

Okay, new question then: is it possible for me to move your mod's textures to overwrite the dog ones in this texture pack? Moving it down the load order doesn't seem to solve the problem. I love this texture pack and would prefer to keep using it. 

Totally understand if this is asking too much - I know I could probably start googling how to minecraft mod and try and learn...

**Comment by itsmeow** [comment]
You could take our assets from github (just press download as zip on the correct branch, extract, src/main/resources will have them) and make a resource pack (just add a pack.mcmeta alongside the assets folder and zip it) and place that at a higher priority. Another option is to open the pack you are using and delete the wolf textures. They might be using Optifine model stuff as well

**Comment by AdmAerrol** [comment]
Got it! Thanks for all your help - it looks like it was, as you suggested, optifine. I went and replaced both the optifine and the regular textures, and that did the trick. Very much appreciated - I learned something new about the basics of how all this stuff fits together (though I started trying to see if I could open .jar files and realized that was over my head for now...). 

Cheers!

**Comment by itsmeow** [comment]
By the way, Optifine has a button in the settings menu to disable this, you don't have to edit the packs and stuff. Just turn off animal variants or entity textures or something in the Optifine settings. I forgot the exact name.

**Comment by AdmAerrol** [comment]
...I had no idea - that's way easier. Thanks for thinking of me so much
later on!
