### ISSUE TITLE
Configuration not working (cannot disable)

### ISSUE THREAD

**Issue by itsmeow** [cybercat5555/BetterAnimals#33]

**Comment by itsmeow** [comment]
Can't find a reliable way to produce this- if anyone knows, please let me know.

**Comment by itsmeow** [comment]
Found how to reproduce: The config can load after MODELREGISTRY in very large modpacks. The overrides should not occur until the config loads. Defer it.

**Comment by NoMaD76** [comment]
Hey man, what do you mean defer it? disable of cats wolves and foxes not working. I have modpack revamped wolves which adds armor to wolves so just want default. How do I do that?

**Comment by itsmeow** [comment]
I was noting to myself what to do on the dev side. There's nothing you can do, aside from reduce the size of your pack mod wise.

**Comment by NoMaD76** [comment]
hey thanks responding so quickly. I'm not understanding: reduce the size of your pack mod wise? you mean taking a mod pack out? or..
Normally with a recource pack you can just take the files out but the modpack wont let you do that? lycanites redux for example made it into a resource pack so you can pick and choose.. nice work btw :) thanks again

**Comment by itsmeow** [comment]
I mean reducing the amount of "mods" in your "mod pack". A mod pack is a collection of mods, a "mod" is an individual jar file that adds content.

Having more mods changes loading times, which causes the config to load *after* Better Animal Models tries to replace the models, thus causing this issue.

**Comment by NoMaD76** [comment]
Ah yeah haha.. terminology.. so I have a collection of 88 mods to make a "modpack" ..I see.. so guess that is a lot ey. Plus 10 resource packs which i all been modifying to make it all "fit" together nicely to some extend with the Patrix textures and that. Guess only way to "fix" it is to make it into a resource pack? can't have config obviously but then you can jus6t take out what you don't want? Thanks letting me know mate, appreciate it. 

love both the packs btw, animals plus, the squirrels, bird, butterflies, geese,  just are all so ace, just adds that atmospheric touch !
