### ISSUE TITLE
Crashing on Vault Hunters Modpack. (Quark ver r2.4 278)

### ISSUE THREAD

**Issue by varjak0** [cybercat5555/BetterAnimals#37]
Adding the better animals mod is the only change I made. Crash log attached. 
[crash-2021-04-02_15.20.08-fml.txt](https://github.com/itsmeow/BetterAnimals/files/6249959/crash-2021-04-02_15.20.08-fml.txt)

**Comment by itsmeow** [comment]
Quark moved their classes again -_-

**Comment by itsmeow** [comment]
Actually it appears you are on a ?supported version?
Can you try 280?

**Comment by coffinbag** [comment]
I am not running the vault hunters mod pack, but I am encountering this issue as well.

I am on forge 36.1.0, minecraft 1.16.5. I disable quark, this mod loads fine, disable this mod and quark loads with no issues either.

here is my crash log.
[New Paste 1.txt](https://github.com/itsmeow/BetterAnimals/files/6557347/New.Paste.1.txt)

**Comment by itsmeow** [comment]
"Failed loading config file oreexcavation-common.toml of type COMMON for modid oreexcavation"
this log doesn't seem to have anything meaningful to the mod? @coffinbag

**Comment by coffinbag** [comment]
could have sworn that was the right log, one moment

**Comment by coffinbag** [comment]
Ok, this one should be the correct crash log, sorry about that.
[crash-2021-05-27_19.45.18-client.txt](https://github.com/itsmeow/BetterAnimals/files/6557442/crash-2021-05-27_19.45.18-client.txt)
