### ISSUE TITLE
Strange Crash with Chikens and Spider doesnt change.

### ISSUE THREAD

**Issue by SirAron111** [cybercat5555/BetterAnimals#8]
There seems to be a problem with the Chickens. First of all, all normal chickens are normal models and all chickens from abyssal craft crash the game. Here is the log. I don’t know if it seems to be some kind of mod incompatibility but I don’t know what. Tested it without Optifine but it still crashed! https://pastebin.com/ne3xpQFp

**Comment by SirAron111** [comment]
And Spiders normal spiders dont change to the nicer ones like the aanti spider next to it.
![2019-05-08_17 33 24](https://user-images.githubusercontent.com/39855956/57389034-ab662f80-71b9-11e9-9987-a3d37199be60.png)

**Comment by itsmeow** [comment]
Can you redownload from curse (delete and readd) to make sure the issue still exists? This may be our alpha build that went up a few days ago. We only fixed things yesterday.

**Comment by SirAron111** [comment]
cant be i just now added and tried the mod out about 1 hour ago or 2

**Comment by itsmeow** [comment]
Another mod is overwriting the spider renderer I think, vanilla spiders don't look like that

**Comment by itsmeow** [comment]
I think I've got it all working on my end. I'm 100% another mod is messing with the spider.
![image](https://user-images.githubusercontent.com/10366817/57409766-1f530880-71b7-11e9-93a4-f2b5dba2ad3c.png)
I'll get this patched ASAP.

**Comment by SirAron111** [comment]
K I will have a look at the spider later maybe i find out what makes it look like this but the chickens did crash XD.
